--- #YAML:1.0
name:               Medical-ICD10
version:            0.02
abstract:           ICD10 Wrapper module
author:
    - Spiros Denaxas <s.denaxas@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:  0
    Data::Dumper:     0
    File::Temp:       0
    Graph:            0
    Test::Deep:       0
    Test::More:       0
    Text::CSV:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
